apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik
  labels:
    name: traefik
    app: traefik
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 128Mi
  volumeMode: Filesystem
